name: Build Desktop Installer

on:
  workflow_dispatch:
jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build installer
        run: npx electron-builder --win
        env:
          NODE_OPTIONS: --max_old_space_size=8192
      
      - name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Installer
          path: dist/*.exe
